Cleaned up
Signed-off-by: eraly <susan.eraly@gmail.com>

diff --git a/java-testing/ignores/parse-for-ignores b/java-testing/ignores/parse-for-ignores
--- a/java-testing/ignores/parse-for-ignores
+++ b/java-testing/ignores/parse-for-ignores
@@ -14,9 +14,8 @@
 #		LIST_OF_TEST_DIRS
 ###############################################################################
 
-set -o errexit
+#set -o errexit
 set -o pipefail
-
 
 ###############################################################################
 # Checks if supplied test class is ingored in entirety
@@ -25,9 +24,8 @@ set -o pipefail
 #   1) Java test file name
 ###############################################################################
 ignored_all() {
-  cat $1 \
-    | perl -pe 's/(^\s*\/\/|\s+\/\/).*$//' \
-    | perl -pe 's/\n/\g/' \
+  perl -pe 's/(^\s*\/\/|\s+\/\/).*$//' < "$1" \
+    | tr -d "\n" \
     | perl -pe \
         's/\@Ignore(\((\".*?\")\))*.*?public\s+class\s+(\S+)/\nFLAG,$2\n/g' \
     | grep ^FLAG \
@@ -41,13 +39,12 @@ ignored_all() {
 #   1) Java test file name
 ###############################################################################
 ignored_tests() {
-  cat $1 \
-    | perl -pe 's/(^\s*\/\/|\s+\/\/).*$//' \
-    | perl -pe 's/\n/\g/' \
-    | perl -pe \
-        's/\@Ignore(\((\".*?\")\))*.*?public\s+void\s+(\S+)\(/\nFLAG$3,$2\n/g' \
-    | grep ^FLAG \
-    | perl -pe 's/FLAG//g'\
+ perl -pe 's/(^\s*\/\/|\s+\/\/).*$//' < "$1" \
+   | tr -d "\n" \
+   | perl -pe \
+     's/\@Ignore(\((\".*?\")\))*.*?public\s+void\s+(\S+)\(/\nFLAG$3,$2\n/g' \
+   | grep ^FLAG \
+   | perl -pe 's/FLAG//g'
 }
 
 ###############################################################################
@@ -56,40 +53,45 @@ ignored_tests() {
 #  None
 ###############################################################################
 parse_test_dirs() {
-  
-  echo "IGNORED/ALL IGNORED:PROJECT,\
-						    PACKAGE NAME, TEST CLASS, TEST METHOD, \
-							IGNORED COMMENT, LOCAL PATH TO TEST CLASS"
+  #header for csv
+  echo -n "IGNORED/ALL IGNORED:"
+  echo -n "PROJECT,PACKAGE NAME, TEST CLASS, TEST METHOD,"
+  echo "IGNORED COMMENT, LOCAL PATH TO TEST CLASS"
+ 
+  for test_dir in ${LIST_OF_TEST_DIRS[@]}; do
 
-  for test_dir in "${LIST_OF_TEST_DIRS[@]}"; do
-	echo -e "\nRunning in subdir $test_dir..."
+	echo -e "\nINFO:Running in subdir $test_dir..."
+    list_of_test_files=$(find "$test_dir" -type f -name *.java)
    
-	#Java files under test directory
-    list_of_test_files=$(find $test_dir -type f -name *.java)
-    for test_file in "${list_of_test_files[@]}"; do
-      echo -e "\tChecking test file $test_file..."
-	  test_file_name=$(basename $test_file)
+    for test_file in ${list_of_test_files[@]}; do
+
+      echo "INFO:Checking test file "$test_file"..."
+	  test_file_name=$(basename "$test_file")
       test_class=${test_file_name%java}
-      package_name=$(grep -e "^\s*package" $test_file \
+      package_name=$(grep -e "^\s*package" "$test_file" \
 					  | awk '{print $2}' \
 					  | tr -d ';')
+
       #Check if entire test class is ignored, if ignored continue to next 
-      all_ignored=$(ignored_all "$test_file") || true
+      all_ignored=$(ignored_all "$test_file") 
       if [ -n "$all_ignored" ]; then
-        echo "ALL IGNORED:$PROJECT_DIR,\
-						  $package_name, $test_class, $all_ignored, $test_file"
+        echo -n "ALL IGNORED:$PROJECT_DIR"
+        echo ",$package_name, $test_class, $all_ignored, $test_file"
         continue
       fi
+
       #Check for ignored tests in test class
-      tests_ignored=$(ignored_tests "$test_file") || true
+      tests_ignored=$(ignored_tests "$test_file")
       if [ -n "$tests_ignored" ]; then       
         while read -r line; do
-            echo "IGNORED:$PROJECT_DIR,\
-						  $package_name, $test_class, $line, $test_file"
+            echo -n "IGNORED:$PROJECT_DIR,"
+			echo "$package_name, $test_class, $line, $test_file"
         done <<< "$tests_ignored"
       fi
+
     done
-    echo -e "Finished running subdir $test_dir"
+    echo "INFO:Finished running subdir $test_dir"
+
   done
 }
 
@@ -100,31 +102,35 @@ parse_test_dirs() {
 #			src/test
 ###############################################################################
 main() {
+  declare PROJECT_DIR="$1"
   if [[ -z $LIBND4J_HOME ]]; then
-   echo "ERROR: LIBND4J_HOME is either unset or set to a non-empty string.\
-  	Set LIBND4J_HOME and rerun.Exiting script..." 1>&2
-   exit 13 
+    echo -n "ERROR: LIBND4J_HOME is either unset or set to a non-empty string."
+    echo -n "Set LIBND4J_HOME and rerun.Exiting script..." 1>&2
+    exit 13 
+  else
+    DL4J_BASE_DIR=`dirname $LIBND4J_HOME`
+    echo -e "\nINFO:Found DL4J base dir: $DL4J_BASE_DIR"
+    test_path="${DL4J_BASE_DIR}/${PROJECT_DIR}"
+    echo -e "\nINFO:Running checks on: ${test_path}\n"
   fi
   
-  DL4J_BASE_DIR=`dirname $LIBND4J_HOME`
-  echo -e "\nFound DL4J base dir: $DL4J_BASE_DIR"
-  
-  PROJECT_DIR=$1
-  test_path="${DL4J_BASE_DIR}/${PROJECT_DIR}"
-  echo -e "\nRunning checks on: ${test_path}"
-  
   if [[ ! -d "$test_path" ]]; then
-    echo -e "ERROR: $test_path DOES NOT exist. \
-  		   Supplied paths have to be relative to the deeplearning4j base dir, \
-  		   i.e the parent dir of libnd4j,nd4j etc\nExiting script..." 1>&2
+    echo -n "ERROR: $test_path DOES NOT exist. "
+    echo -n "Supplied paths have to be relative to the deeplearning4j base dir"
+    echo -n ", i.e the parent dir of libnd4j,nd4j etc\nExiting script..." 1>&2
     exit 7
+  else
+    LIST_OF_TEST_DIRS=$(find $test_path -path *src/test)
+  fi
   
-  LIST_OF_TEST_DIRS=$(find $test_path -path *src/test)
-  
-  if [[ -n "$LIST_OF_TEST_DIRS" ]]; then
-    echo -e "ERROR: NO src/test directories under $test_path" 1>&2
+  if [[ -z "$LIST_OF_TEST_DIRS" ]]; then
+    echo "ERROR: NO src/test directories under $test_path" 1>&2
     exit 8
-  parse_test_dirs()
+  fi
+
+  parse_test_dirs
+
+  echo -e "\n\nINFO: Run completed."
 }
 
 ###############################################################################
